% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:26:18+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(abe, bea).
parent(cia, bea).
parent(xia, yan).
parent(yan, zed).
parent(zed, abe).
