% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:27:01+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(sora, tia).
parent(tia, uma).
parent(uma, vero).
parent(vero, wren).
