% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T16:13:46+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(jordan, pat).
parent(pat, taylor).
parent(taylor, riley).
