% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:26:23+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(ari, bo).
parent(bo, cy).
parent(cy, di).
parent(di, eli).
parent(fay, eli).
parent(fay, gus).
