% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-09T23:56:20+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
man(plato).
man(socrates).
mortal(X) :- man(X).
parent(alice, bob).
parent(bob, carol).
