% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-15T04:45:47+00:00

ate(goldilocks, porridge).
belongs_to(house, baby_bear).
belongs_to(house, mama_bear).
belongs_to(house, papa_bear).
fits_goldilocks(baby_bear_bed, goldilocks).
fits_goldilocks(porridge_of_baby_bear, goldilocks).
goldilocks(little_girl).
goldilocks_found(goldilocks, small_house).
has_bed(baby_bear, small_bed).
has_bed(mama_bear, medium_bed).
has_bed(papa_bear, big_bed).
has_chair(baby_bear, small_chair).
has_chair(mama_bear, medium_chair).
has_chair(papa_bear, big_chair).
has_porridge(baby_bear, small_bowl_of_porridge).
has_porridge(mama_bear, medium_bowl_of_porridge).
has_porridge(papa_bear, big_bowl_of_porridge).
ran_out_of(goldilocks, house).
returned_home(bears).
sat_in(goldilocks, chair).
sat_in(goldilocks, mama_bear_chair).
saw(baby_bear, ate(someone, porridge_of(baby_bear))).
saw(mama_bear, sat_in(someone, chair_of(mama_bear))).
saw(mama_bear, tasted(someone, porridge_of(mama_bear))).
saw(mama_bear, that_someone_had_been_lying).
saw(papa_bear, sat_in(someone, chair_of(papa_bear))).
saw(papa_bear, tasted(someone, porridge_of(papa_bear))).
saw(papa_bear, that_someone_had_been_lying).
slept_in(goldilocks, baby_bear_bed).
slept_in(goldilocks, bed).
slept_in(goldilocks, mama_bear_bed).
slept_in(goldilocks, papa_bear_bed).
slept_in(that_someone_had_been_lying, bed_of(mama_bear)).
slept_in(that_someone_had_been_lying, bed_of(papa_bear)).
tasted(goldilocks, porridge).
too_cold(mama_bear_porridge, goldilocks).
too_hard(chair_of_papa_bear, goldilocks).
too_hard(papa_bear_bed, goldilocks).
too_hot(papa_bear_porridge, goldilocks).
too_soft(chair_of_mama_bear, goldilocks).
too_soft(mama_bear_bed, goldilocks).
walked_through_forest(goldilocks).
went_upstairs(bears).
