% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-10T16:17:06+00:00

chairs_in_house(baby_bear, baby_bear).
chairs_in_house(chairs).
chairs_in_house(medium).
chairs_in_house(papa_bear_chair).
chairs_in_house(small_chair).
fits_goldilocks(baby_bear_bed, goldilocks).
goldilocks(little_girl).
goldilocks_found(baby_bear_bed).
goldilocks_found(goldilocks, papa_bear_porridge).
goldilocks_found(mama_bear_bed).
goldilocks_found(papa_bear_bed).
goldilocks_found(small_house, forest).
has_porridge(goldilocks, baby_bear).
has_porridge(goldilocks, mama_bear).
has_porridge(goldilocks, mama_bear_chair).
has_porridge(mama_bear, medium).
has_porridge(papa_bear).
returned_home(bears).
returned_home(goldilocks).
returned_home(the_three_bears).
saw(baby_bear, goldilocks).
saw(goldilocks, bear1).
tasted(goldilocks, porridge_of_papa_bear).
too_cold(goldilocks, porridge).
too_hard(goldilocks, papa_bear_bed).
too_hard(papa_bear_chair, goldilocks).
too_hot(papa_bear_porridge).
too_soft(mama_bear_bed).
too_soft(mama_bear_chair, goldilocks).
