% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:24:07+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(aiden, bella).
parent(bella, cal).
parent(cal, dana).
