% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:11:39+00:00

guides(X, Y) :- mentors(X, Y).
guides(X, Y) :- supervises(X, Y).
guides(X, Z) :- guides(X, Y), guides(Y, Z).
mentors(gina, harper).
supervises(harper, ivan).
