% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T15:44:16+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
endorsed(X) :- ancestor(X, Y), trusted(Y).
parent(pru, ria).
parent(ria, quin).
parent(sara, pru).
trusted(ria).
