% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-10T05:39:42+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
father(liam, noah).
parent(X, Y) :- father(X, Y).
parent(noah, owen).
