% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:27:59+00:00

auth_mode(wrangler, cli_scoped_token).
auth_mode(wrangler, oauth).
auth_mode(wrangler, static_token).
dislikes(jFriedensreich, wrangler).
