% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:25:44+00:00

occasionally_holds(nim_talks, fosdem).
occasionally_holds(talk_topic(nim), fosdem).
talk_topic(elcritch, figdraw_and_neovim_ui_shell).
teaches(modern_mech, freshman_lua).
teaches(modern_mech, programming_languages).
