% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-12T03:17:54+00:00

at(aria, market).
at(mara, market).
at(silas, market).
has_item(aria, healing_herb).
soaked(aria, insomnia).
time_of_day(day).
weather(clear).
