% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:28:40+00:00

6).
has_buggy_support(amd).
has_buggy_support(amd, roc).
has_buggy_support(roc, rx_580).
has_catching_up_task(amd, roc).
has_hiring_issue(amd).
has_hiring_issue(amd, software_engineers).
has_instability(amd, linux_amdgpu_driver).
has_instability(amd, roc).
has_instability(amd_rocm).
has_instability(roc_m, server_grade_hardware_only).
has_unstable_driver(amd, linux, 6.
