% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:25:26+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(juno, kai).
parent(kai, lark).
parent(mira, juno).
