% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:22:48+00:00

coding_quantization_limit(coding, q6_k).
worth_it(X, Q4) :- chatting(X).
worth_it(X, Q4) :- coding(X), not_precision(X).
worth_it(X, Q8) :- chatting(X).
worth_it(X, Q8) :- coding(X), not_precision(X).
worth_it(X, false) :- coding(X), coding_quantization_limit(X).
worth_it(X, false) :- coding(X), not_precision(X), coding_quantization_limit(X).
worth_it(X, true) :- chatting(X).
worth_it(X, true) :- coding(X), not_precision(X).
