% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-10T05:51:38+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(ava, ben).
parent(ben, cora).
parent(cora, dean).
parent(dean, emma).
related_to(X, Y) :- parent(X, Y).
related_to(X, Z) :- related_to(X, Y), related_to(Y, Z).
