% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T04:14:48+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(pax, toma).
parent(rhea, pax).
parent(toma, sia).
parent(uma, sia).
