% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T16:59:14+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(bea, zed).
parent(wes, ava).
parent(wes, yan).
parent(yan, bea).
