% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-10T05:49:45+00:00

allowed(X) :- has_override(X).
blocked(X) :- has_manual_review(X).
blocked(X) :- provisional(X).
has_manual_review(a3).
provisional(a3).
risky(X) :- blocked(X), allowed(X).
valid(a4).
