% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:31:10+00:00

based_in(bakto_flavors, nj_usa).
bought(jackdawed, carbonator).
clubmate_recipe(60g_mate, 500ml_water, 65g_sugar, 1_lemon, soda_water).
focused_on(dr_daphna_havkin_frenkel, vanilla).
founded_by(bakto_flavors, dr_daphna_havkin_frenkel).
passed_away(dr_daphna_havkin_frenkel, recently).
recommended(bakto_flavors, natural_flavors).
research_field(dr_daphna_havkin_frenkel, biotechnology).
research_field(dr_daphna_havkin_frenkel, food_sciences).
