% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-15T00:07:02+00:00

completed(console_submission).
completed(crash_triage_sweep).
completed(final_build_candidate).
completed(platform_release_slot).
completed(vertical_slice_lock).
depends_on(console_submission, final_build_candidate).
depends_on(day_one_patch, final_build_candidate).
depends_on(global_launch, console_submission).
depends_on(global_launch, day_one_patch).
depends_on(global_launch, matchmaking_scale_test).
depends_on(matchmaking_scale_test, final_build_candidate).
depends_on(platform_release_slot, console_submission).
milestone(global_launch).
set_task(console_submission, console_cert_vendor).
set_task(day_one_patch).
set_task(global_launch).
set_task(matchmaking_scale_test).
set_task(platform_release_slot).
supplier_status(cloud_vendor, delayed).
supplier_status(cloud_vendor, on_time).
supplier_status(console_cert_vendor, delayed).
supplier_status(console_cert_vendor, on_time).
supplier_status(set_supplier, delayed).
task(console_submission).
task(day_one_patch).
task(final_build_candidate).
task(global_launch).
task(matchmaking_scale_test).
task(platform_release_slot).
task_supplier(console_submission, console_cert_vendor).
task_supplier(matchmaking_scale_test, cloud_vendor).
