% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-11T17:12:52+00:00

ancestor(X, Y) :- parent(X, Y).
ancestor(X, Z) :- parent(X, Y), ancestor(Y, Z).
parent(uma, tess).
parent(wren, uma).
parent(xena, wren).
