% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-15T07:30:20+00:00

activated(jax, jetpack).
asked_if_occupied(jax, chrome_plated_dome_station).
blew_fuse(sonic_zips).
bounced_off(jax, ceiling).
caused_effect(eco_cell, swallowed_molasses_feeling).
caused_effect(mega_cell, glowing_green_teeth).
caused_effect(nano_cell, jetpack_crystalline_energy).
caused_effect(titan_boots, could_not_lift_feet).
charred(sonic_zips).
climbed_into(jax, bio_hammock).
docked_at(jax, chrome_plated_dome_station).
has_habit(jax, borrows_oxygen_without_permission).
has_item(chrome_plated_dome_station, eco_cell).
has_item(chrome_plated_dome_station, hover_slippers).
has_item(chrome_plated_dome_station, mega_cell).
has_item(chrome_plated_dome_station, nano_cell).
has_item(chrome_plated_dome_station, sonic_zips).
has_item(chrome_plated_dome_station, titan_boots).
has_item(unit_alpha, cryo_chamber).
has_item(unit_alpha, high_grade_isotopes).
has_item(unit_alpha, titan_boots).
has_item(unit_beta, hover_slippers).
has_item(unit_beta, memory_foam_cloud).
has_item(unit_beta, organic_fuel).
has_item(widget, bio_hammock).
has_item(widget, nano_cell).
has_item(widget, sonic_zips).
has_trait(jax, neon_blue_hair).
hit(jax, head).
hoped_for(widget, leave_review_on_galactic_map(jax)).
is_a(jax, freelance_space_salvager).
just_right_for(bio_hammock, jax).
just_right_for(nano_cell, jax).
just_right_for(sonic_zips, jax).
liked(jax, fuel_of(widget)).
located_in(bio_hammock, sleeping_quarters).
located_in(cryo_chamber, sleeping_quarters).
located_in(eco_cell, galley_charging_station).
located_in(hover_slippers, mudroom).
located_in(mega_cell, galley_charging_station).
located_in(memory_foam_cloud, sleeping_quarters).
located_in(nano_cell, galley_charging_station).
located_in(sonic_zips, mudroom).
located_in(titan_boots, mudroom).
moved_in(jax, sonic_zips).
performed(jax, zero_gravity_backflip_through_airlock).
pushed_too_hard(jax, sonic_zips).
reported(unit_alpha, biological_entity_in(cryo_chamber)).
reported(unit_alpha, calibrate_attempt(titan_boots)).
reported(unit_alpha, siphoned(high_grade_isotopes)).
reported(unit_beta, compressed(memory_foam_cloud)).
reported(unit_beta, scuff_marks(hover_slippers)).
reported(unit_beta, tasted(organic_fuel)).
reported(widget, drank(nano_cell)).
reported(widget, emptied(vial)).
reported(widget, fried(sonic_zips_motherboards)).
returned_from(unit_alpha, morning_spacewalk).
returned_from(unit_beta, morning_spacewalk).
returned_from(widget, morning_spacewalk).
saw(jax, unit_alpha).
saw(jax, unit_beta).
saw(jax, widget).
saw(widget, asleep_in(jax, bio_hammock)).
scouting_in(jax, nebula_sector).
sipped(jax, eco_cell).
sipped(jax, mega_cell).
sipped(jax, nano_cell).
slept_in(jax, bio_hammock).
station_silent(chrome_plated_dome_station).
stepped_into(jax, titan_boots).
thrusters_flickered_out(jax).
too_cold(cryo_chamber, jax).
too_floaty(hover_slippers, jax).
too_heavy(titan_boots, jax).
too_radioactive(mega_cell, jax).
too_sluggish(eco_cell, jax).
too_squishy(memory_foam_cloud, jax).
tried(jax, cryo_chamber).
tried(jax, hover_slippers).
tried(jax, memory_foam_cloud).
vanished_into(jax, starfield).
woke_up(jax).
wore(jax, sonic_zips).
