% Auto-generated by kb_pipeline.py
% Updated UTC: 2026-04-14T17:25:06+00:00

enjoyment_motivation(X, Y) :- require_money(X, Y), lower_quality(X, Y).
enjoyment_motivation(X, Y) :- require_money(X, Y).
enjoyment_motivation(corporation, 'makes thousands off their work without paying anything back').
enjoyment_motivation(free_workers).
enjoyment_motivation(jcalvinowens).
lower_quality(X, Y) :- do_something(X, Y).
waste_time(free_workers, working_for_money).
